out_dir: results
num_workers: 3
dataset:
  format: PyG
  name: TU_MUTAG
  task: graph
  task_type: classification
  node_encoder: false
  edge_encoder: false
  split_mode: random
  split: [0.6, 0.2, 0.2]
share:
  num_splits: 3
train:
  batch_size: 128
  eval_period: 1
  ckpt_period: 50
  sampler: full_batch
model:
  type: globalpoolgnn
  loss_fun: cross_entropy
  graph_pooling: sortpool
gnn:
  layers_pre_mp: 0
  layers_mp: 2
  layers_post_mp: 0
  dim_inner: 32
  layer_type: sageconv
  stage_type: stack
  batchnorm: false
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: false
  head: mlp_head
global_pooling:
  post_pool_layer: post_pool_linear
  post_pool_dropout: 0.5
mlp_head:
  num_layers: 1
  dropout: 0.0
optim:
  optimizer: adam
  base_lr: 0.01
  max_epoch: 100
